export {
  assertJSONValue,
  isJSONValue,
  materializeToolCall,
  materializeToolCalls,
  materializeToolResult,
  materializeToolResultAsync,
  materializeToolResults,
  materializeToolResultsAsync,
} from './materialization';
export type { MaterializeToolCallOptions, MaterializeToolResultOptions } from './materialization';
export type {
  JSONArray,
  JSONObject,
  JSONPrimitive,
  JSONValue,
  ToolAction,
  ToolActionInput,
  ToolApprovalAction,
  ToolApprovalCommandOperation,
  ToolApprovalFileWriteOperation,
  ToolApprovalOperation,
  ToolApprovalOtherOperation,
  ToolApprovalPatchOperation,
  ToolApprovalResolution,
  ToolApprovalResolutionDecision,
  ToolApprovalRisk,
  ToolApprovalSandbox,
  ToolCall,
  ToolCallInput,
  ToolError,
  ToolErrorCategory,
  ToolErrorInput,
  ToolPolicy,
  ToolResult,
  ToolResultInput,
} from './types';
