export type {
  CompactionOptions,
  CompactionPreservePolicy,
  CompactionResult,
  Summarizer,
} from './compaction/index';
export { compactConversation, stripToolResultDetails } from './compaction/index';
export type {
  ConditionalInstructionComposer,
  ConditionalInstructionComposerRenderOptions,
  ConditionalInstructionSection,
  InstructionComposer,
  InstructionComposerRenderOptions,
  InstructionContext,
  InstructionSection,
  InstructionTemplate,
  MissingVariableStrategy,
  SectionsToMessageInputsOptions,
  TemplateOptions,
} from './composition/index';
export {
  createConditionalInstructionComposer,
  createInstructionComposer,
  createInstructionTemplate,
  extractTemplateVariables,
  renderTemplate,
  sectionsToMessageInputs,
  whenAnyToolAvailable,
  whenMetadata,
  whenMetadataPresent,
  whenStep,
  whenToolsAvailable,
} from './composition/index';
export type {
  AppendToolCallOptions,
  AppendToolResultOptions,
  BuildMessageOptions,
  ConversationEnvironment,
  IntegrityIssue,
  IntegrityIssueCode,
  MaterializeToolCallOptions,
  RedactMessageOptions,
  ToolInteraction,
} from './conversation/index';
export {
  appendAssistantMessage,
  appendMessages,
  appendSystemMessage,
  appendToolCall,
  appendToolCalls,
  appendToolResult,
  appendToolResultAsync,
  appendToolResults,
  appendToolResultsAsync,
  appendUnsafeMessage,
  appendUserMessage,
  assertConversationHistoryIntegrity,
  buildMessage,
  collapseSystemMessages,
  createConversationHistory,
  createConversationHistoryUnsafe,
  deserializeConversationHistory,
  getFirstSystemMessage,
  getMessageAtPosition,
  getMessageById,
  getMessageIds,
  getMessages,
  getPendingToolCalls,
  getStatistics,
  getSystemMessages,
  getToolInteractions,
  hasSystemMessage,
  materializeToolCall,
  materializeToolCalls,
  materializeToolResult,
  materializeToolResultAsync,
  materializeToolResults,
  materializeToolResultsAsync,
  prependMessages,
  prependSystemMessage,
  redactMessageAtPosition,
  replaceSystemMessage,
  resolveToolResult,
  searchConversationMessages,
  toChatMessages,
  validateConversationHistoryIntegrity,
} from './conversation/index';
export type { SessionInfo } from './environment';
export { toSessionInfo } from './environment';
export type { ConversationalistErrorCode } from './errors';
export {
  ConversationalistError,
  createDuplicateIdError,
  createInvalidInputError,
  createInvalidPositionError,
  createInvalidToolReferenceError,
  createLockedError,
  createNotFoundError,
  createSerializationError,
  createToolResultNotFoundError,
  createValidationError,
} from './errors';
export type { ConversationEventMap } from './events';
export {
  CompactionCompletedEvent,
  CompactionStartedEvent,
  ConversationChangeEvent,
  ConversationPushEvent,
  ConversationRedoEvent,
  ConversationSwitchEvent,
  ConversationUndoEvent,
  MessagesAppendedEvent,
  MessagesRemovedEvent,
  MessagesUpdatedEvent,
  SessionForkedEvent,
  SessionRenamedEvent,
  SessionTaggedEvent,
  StreamCancelledEvent,
  StreamFinalizedEvent,
  StreamStartedEvent,
  StreamUpdatedEvent,
  ToolCallsAppendedEvent,
  ToolResultsAppendedEvent,
} from './events';
export {
  isConversation,
  isConversationHistory,
  isConversationStatus,
  isJSONValue,
  isMessage,
  isMessageInput,
  isMessageRole,
  isMultiModalContent,
  isTokenUsage,
  isToolCall,
  isToolResult,
} from './guards';
export type {
  ConversationActionType,
  ConversationEvent,
  ConversationEventDetail,
  ConversationEvents,
  ConversationEventType,
} from './history';
export { Conversation } from './history';
export type {
  ContainerUploadContent,
  DocumentContent,
  DocumentSource,
  ImageContent,
  MultiModalContent,
  RedactedThinkingContent,
  ServerToolResultContent,
  ServerToolResultType,
  ServerToolUseContent,
  TextContent,
  ThinkingContent,
  WebSearchToolResultContent,
} from './multi-modal';
export type {
  Projection,
  ProjectionEventIdentity,
  ProjectionOptions,
  ProjectionReducer,
  ProjectionReducerContext,
  ProjectionReducerResult,
} from './projection';
export { createProjection, isProjectionPrefixExtension } from './projection';
export type {
  AppendableToolAction,
  AppendableToolCallInput,
  AppendableToolError,
  AppendableToolResult,
  AssistantMessage,
  ChatMessage,
  ChatMessageRole,
  ConversationHistory,
  ConversationProvider,
  ConversationStatus,
  JSONValue,
  Message,
  MessageInput,
  MessageRole,
  TokenUsage,
  ToolAction,
  ToolActionInput,
  ToolCall,
  ToolCallInput,
  ToolError,
  ToolErrorCategory,
  ToolErrorInput,
  ToolResult,
  ToolResultInput,
} from './types';
export type { ConversationNodeSnapshot, ConversationSnapshot } from './types';
export type { ConversationHistoryDraft } from './with-conversation';
export { pipeConversationHistory, withConversationHistory } from './with-conversation';
