import { $ } from 'bun';

const entrypoints = [
  './src/index.ts',
  // Provider subpaths (folded from herald — dynamically import SDKs, zero-SDK-if-unused)
  './src/anthropic.ts',
  './src/openai.ts',
  './src/gemini.ts',
  './src/providers/index.ts',
  './src/providers/anthropic.ts',
  './src/providers/openai.ts',
  './src/providers/gemini.ts',
  './src/providers/errors.ts',
  './src/providers/types.ts',
  './src/providers/shared/resolve-common-parameters.ts',
  './src/providers/structured-output/index.ts',
  './src/providers/structured-output/types.ts',
  './src/providers/streaming/index.ts',
  './src/providers/streaming/normalize-anthropic.ts',
  './src/providers/streaming/normalize-openai.ts',
  './src/providers/fallover/index.ts',
  './src/providers/routing/index.ts',
  './src/providers/embeddings/index.ts',
  './src/providers/embeddings/openai.ts',
  './src/providers/embeddings/gemini.ts',
  './src/providers/embeddings/voyage.ts',
  './src/providers/embeddings/ollama.ts',
  './src/providers/instrumentation/index.ts',
  './src/providers/test/index.ts',
  './src/create-run.ts',
  './src/loop.ts',
  './src/errors.ts',
  './src/events.ts',
  './src/generate-middleware.ts',
  './src/streaming.ts',
  './src/types.ts',
  './src/create-scratchpad.ts',
  './src/create-agent-registry.ts',
  './src/create-supervisor.ts',
  './src/create-subagent-tool.ts',
  './src/create-early-stopping-handler.ts',
  './src/create-handoff-tool.ts',
  './src/cost-estimation.ts',
  './src/cost-budget-monitor.ts',
  './src/agent-session.ts',
  './src/backpressure.ts',
  './src/create-context-compactor.ts',
  './src/create-identity-hook.ts',
  './src/create-memory-bridge.ts',
  './src/create-policy-enforcement-hook.ts',
  './src/cache/index.ts',
  './src/cache/types.ts',
  './src/cache/cache-keys.ts',
  './src/cache/with-cache.ts',
  './src/cache/cache-metrics.ts',
  './src/cache/cache-utilities.ts',
  './src/conditions/index.ts',
  './src/conditions/predicates.ts',
  './src/instrumentation/index.ts',
  './src/scheduler/index.ts',
  './src/scheduler/types.ts',
  './src/scheduler/priority-queue.ts',
  './src/scheduler/sleep.ts',
  './src/scheduler/events.ts',
  './src/scheduler/create-scheduler.ts',
  './src/scheduler/create-durable-heartbeat.ts',
  './src/scheduler/create-heartbeat.ts',
  './src/scheduler/create-chunked-task.ts',
  './src/durable/index.ts',
  './src/session/index.ts',
  './src/session/types.ts',
  './src/session/create-session-store.ts',
  './src/session/session-resume.ts',
  './src/structured-output/index.ts',
  './src/test/index.ts',
  './src/context/index.ts',
  './src/context/token-budget.ts',
  './src/context/assembly.ts',
  './src/context/compaction-strategies.ts',
  './src/context/subagent-context.ts',
  './src/context/types.ts',
  './src/guardrails/index.ts',
  './src/guardrails/types.ts',
  './src/guardrails/input-guardrail.ts',
  './src/guardrails/output-guardrail.ts',
  './src/guardrails/session-taint.ts',
  './src/guardrails/create-guardrails.ts',
  './src/guardrails/validators/grounding.ts',
  './src/guardrails/validators/output-pii.ts',
  './src/guardrails/validators/code-safety.ts',
  './src/hooks/index.ts',
  './src/hooks/types.ts',
  './src/hooks/composition.ts',
  './src/streaming/index.ts',
  './src/store/index.ts',
  './src/streaming/types.ts',
  './src/streaming/stream-state-machine.ts',
  './src/streaming/enhanced-streaming.ts',
  './src/streaming/backpressure-buffer.ts',
  './src/retry/index.ts',
  './src/retry/types.ts',
  './src/retry/jitter.ts',
  './src/retry/overflow-mutator.ts',
  './src/retry/tool-removal-mutator.ts',
  './src/retry/temperature-escalation-mutator.ts',
  './src/retry/schema-error-mutator.ts',
  './src/retry/compose-mutators.ts',
];

const root = './src';

await $`rm -rf dist`;

await Bun.build({
  entrypoints,
  outdir: './dist',
  root,
  target: 'bun',
  format: 'esm',
  naming: '[dir]/[name].js',
  sourcemap: 'external',
  minify: true,
});

await $`bunx tsc --declaration --emitDeclarationOnly --project tsconfig.build.json`;

await Bun.build({
  entrypoints,
  outdir: './dist',
  root,
  target: 'node',
  format: 'cjs',
  naming: '[dir]/[name].cjs',
  sourcemap: 'external',
  minify: true,
});

console.log('Build complete!');
