import type { ToolPolicy } from '@lostgradient/tool-protocol';

export type { ToolPolicy };

// ── Skill Metadata and Content ───────────────────────────────────────

/**
 * Metadata parsed from a SKILL.md frontmatter.
 * Follows the Agent Skills specification: https://agentskills.org
 */
export interface SkillMetadata {
  /** Skill name in kebab-case. */
  name: string;
  /** What the skill does and when the model should use it. */
  description: string;
  /** License for the skill. */
  license?: string;
  /** Compatibility notes (e.g., "Requires exec tool and filesystem access"). */
  compatibility?: string;
  /** Tool policy: which armorer tools this skill can use when active. */
  toolPolicy?: ToolPolicy;
  /** Arbitrary key-value metadata for client-specific properties. */
  metadata?: Record<string, string>;
}

/**
 * A catalog entry — the tier-1 progressive disclosure level.
 * Contains only name + description (~50-100 tokens per skill), always present in context.
 */
export interface SkillCatalogEntry {
  /** Skill name. */
  name: string;
  /** Skill description. */
  description: string;
  /** Whether the skill is currently active in this session. */
  active?: boolean;
}

/**
 * Full skill content — the tier-2 progressive disclosure level.
 * Loaded when a skill is activated (<5000 tokens recommended).
 */
export interface SkillContent {
  /** Parsed metadata from frontmatter. */
  metadata: SkillMetadata;
  /** The markdown body (instructions). */
  body: string;
}

/**
 * A bundled resource — the tier-3 progressive disclosure level.
 * Loaded on demand when instructions reference them.
 */
export interface SkillResource {
  /** Relative path within the skill directory (e.g., "scripts/extract.py"). */
  path: string;
  /**
   * Raw resource content.
   *
   * Bytes rather than a string because a skill bundle legitimately carries images, fonts and
   * other binary assets, and decoding one as UTF-8 replaces every invalid sequence with U+FFFD —
   * silent, irreversible corruption. Decoding is the caller's decision, made per resource at the
   * point where text is actually needed.
   */
  content: Uint8Array;
}

// ── Skill Provider ───────────────────────────────────────────────────

/**
 * The interface platform adapters implement for skill storage/retrieval.
 * Follows the storage-first model: skills are strings in the shared storage adapter,
 * not files on disk.
 */
/**
 * Persists skills into a durable store.
 *
 * Writes only. Reading skills back is discovery's job — a skill admitted through a read method
 * here would have no catalog entry, no trust decision, no artifact digest and no compatibility
 * verdict, which is the duplication this interface was narrowed to remove. The self-improvement
 * flow is what genuinely needs a write path: an accepted proposal has to land somewhere the next
 * run's discovery will find it.
 */
export interface SkillWriter {
  /** Save a skill, from ingestion or an accepted self-improvement proposal. */
  saveSkill(name: string, content: SkillContent): Promise<void>;
  /** Delete a skill and everything stored under it. */
  deleteSkill(name: string): Promise<void>;
  /** Save one bundled resource from raw bytes. */
  saveResource(name: string, path: string, content: Uint8Array): Promise<void>;
  /** Set enabled status. An absent value means enabled. */
  setEnabled(name: string, enabled: boolean): Promise<void>;
}

// ── Self-Improvement Types ───────────────────────────────────────────

/**
 * A proposal generated by the self-improvement sweep.
 * Proposals are independently accept/reject — granular, not batch.
 */
export interface Proposal {
  /** Unique proposal ID. */
  id: string;
  /** What kind of change is proposed. */
  type: 'skill' | 'soul' | 'persona';
  /** Human-readable summary of the proposal. */
  summary: string;
  /** The proposed content (full SKILL.md for skills, soul items JSON for soul, persona text for persona). */
  content: string;
  /** Which agent this applies to (undefined = orchestrator). */
  agentId?: string;
  /** Memory entry IDs that informed this proposal (provenance). */
  sourceEntryIds: string[];
  /** When the proposal was generated (ISO 8601). */
  createdAt: string;
  /** Current status. */
  status: 'pending' | 'accepted' | 'rejected';
  /** If rejected, the reason. */
  rejectionReason?: string;
}

// ── Events (COR-767) ─────────────────────────────────────────────────
// COR-767 requires the EventMap to be exported from this module, matching the
// package rule that type re-exports live here rather than in a barrel.
export type {
  SkillAdmissionRule,
  SkillEventClassMap,
  SkillEventCorrelation,
  SkillEventMap,
  SkillEventType,
  SkillRejectionReason,
} from './events';
