import type { IdentityStorageAdapter } from 'memory';

// ── Reusable Policy ──────────────────────────────────────────────────

/**
 * Reusable allow/deny list for both tools and skills.
 * Used by persona tool policies, persona skill policies, and skill tool policies.
 * Deny always wins over allow.
 */
export interface ToolPolicy {
  /** If set, ONLY these are available. */
  allowList?: string[];
  /** These are never available, even if in the allowList. Deny wins. */
  denyList?: string[];
}

// ── Skill Metadata and Content ───────────────────────────────────────

/**
 * Metadata parsed from a SKILL.md frontmatter.
 * Follows the Agent Skills specification: https://agentskills.org
 */
export interface SkillMetadata {
  /** Skill name in kebab-case. */
  name: string;
  /** What the skill does and when the model should use it. */
  description: string;
  /** License for the skill. */
  license?: string;
  /** Compatibility notes (e.g., "Requires exec tool and filesystem access"). */
  compatibility?: string;
  /** Tool policy: which armorer tools this skill can use when active. */
  toolPolicy?: ToolPolicy;
  /** Arbitrary key-value metadata for client-specific properties. */
  metadata?: Record<string, string>;
}

/**
 * A catalog entry — the tier-1 progressive disclosure level.
 * Contains only name + description (~50-100 tokens per skill), always present in context.
 */
export interface SkillCatalogEntry {
  /** Skill name. */
  name: string;
  /** Skill description. */
  description: string;
  /** Whether the skill is currently active in this session. */
  active?: boolean;
}

/**
 * Full skill content — the tier-2 progressive disclosure level.
 * Loaded when a skill is activated (<5000 tokens recommended).
 */
export interface SkillContent {
  /** Parsed metadata from frontmatter. */
  metadata: SkillMetadata;
  /** The markdown body (instructions). */
  body: string;
}

/**
 * A bundled resource — the tier-3 progressive disclosure level.
 * Loaded on demand when instructions reference them.
 */
export interface SkillResource {
  /** Relative path within the skill directory (e.g., "scripts/extract.py"). */
  path: string;
  /** The resource content. */
  content: string;
}

// ── Environment Capabilities ─────────────────────────────────────────

/**
 * Environment capabilities descriptor for eligibility filtering.
 * Skills declare what they need; the runtime declares what it provides.
 */
export interface EnvironmentCapabilities {
  /** Whether the environment can execute scripts/commands. */
  canExecuteScripts: boolean;
  /** Whether the environment has filesystem access. */
  canAccessFilesystem: boolean;
  /** Whether the environment has network access. */
  canAccessNetwork: boolean;
  /** Tool names available in the current armorer toolbox. */
  availableTools: string[];
  /** Platform identifier. */
  platform: 'server' | 'browser' | 'extension' | 'mobile' | 'worker';
}

// ── Skill Provider ───────────────────────────────────────────────────

/**
 * The interface platform adapters implement for skill storage/retrieval.
 * Follows the storage-first model: skills are strings in the shared storage adapter,
 * not files on disk.
 */
export interface SkillProvider {
  /** List all available skills (catalog tier). */
  listSkills(): Promise<SkillCatalogEntry[]>;
  /** Load full skill content (instructions tier). */
  loadSkill(name: string): Promise<SkillContent | undefined>;
  /** Save a skill (from ingestion or self-improvement proposal). */
  saveSkill(name: string, content: SkillContent): Promise<void>;
  /** Delete a skill. */
  deleteSkill(name: string): Promise<void>;
  /** Check if a skill exists. */
  hasSkill(name: string): Promise<boolean>;
  /** List resources bundled with a skill. */
  listResources(name: string): Promise<string[]>;
  /** Load a specific resource. */
  loadResource(name: string, path: string): Promise<string | undefined>;
  /** Save a resource. */
  saveResource(name: string, path: string, content: string): Promise<void>;
  /** Get enabled status. Defaults to true if not explicitly set. */
  isEnabled(name: string): Promise<boolean>;
  /** Set enabled status. */
  setEnabled(name: string, enabled: boolean): Promise<void>;
}

// ── Self-Improvement Types ───────────────────────────────────────────

/**
 * A proposal generated by the self-improvement sweep.
 * Proposals are independently accept/reject — granular, not batch.
 */
export interface Proposal {
  /** Unique proposal ID. */
  id: string;
  /** What kind of change is proposed. */
  type: 'skill' | 'soul' | 'persona';
  /** Human-readable summary of the proposal. */
  summary: string;
  /** The proposed content (full SKILL.md for skills, soul items JSON for soul, persona text for persona). */
  content: string;
  /** Which agent this applies to (undefined = orchestrator). */
  agentId?: string;
  /** Memory entry IDs that informed this proposal (provenance). */
  sourceEntryIds: string[];
  /** When the proposal was generated (ISO 8601). */
  createdAt: string;
  /** Current status. */
  status: 'pending' | 'accepted' | 'rejected';
  /** If rejected, the reason. */
  rejectionReason?: string;
}

/**
 * A cluster of related experiential entries identified by the analysis stage.
 * Informed by AutoRefine's pattern extraction and SkillRL's hierarchical SkillBank.
 */
export interface PatternCluster {
  /** A descriptive name for the cluster. */
  name: string;
  /** The entries in this cluster. */
  entries: Array<{ content: string; metadata: Record<string, unknown>; entryId: string }>;
  /** Whether this cluster represents a strategy, recovery pattern, or optimization. */
  type: 'strategy' | 'recovery' | 'optimization';
  /** Suggested skill name (kebab-case). */
  suggestedSkillName: string;
}

/**
 * Result of the pattern analysis stage.
 * Identifies clusters for skill formation, candidates for soul graduation,
 * and per-agent candidates for persona updates.
 */
export interface PatternAnalysis {
  /** Clusters of related experiential entries. */
  clusters: PatternCluster[];
  /** Entries that are high-confidence, general, and suitable for soul graduation. */
  soulCandidates: Array<{
    content: string;
    confidence: number;
    topic?: string;
    entryId: string;
  }>;
  /** Per-agent entries suitable for persona updates. */
  personaCandidates: Record<
    string,
    Array<{ content: string; confidence: number; entryId: string }>
  >;
}

/**
 * State tracked across self-improvement sweep chunks.
 * Compatible with operative's CreateChunkedTaskOptions<SweepState>.
 */
export interface SweepState {
  /** Experiential entries collected so far. */
  collected: number;
  /** Clusters identified. */
  clusters: number;
  /** Proposal IDs generated. */
  proposals: string[];
  /** Current stage. */
  stage: 'collect' | 'analyze' | 'draft' | 'filter' | 'complete';
}

// ── Storage Adapter Re-export ────────────────────────────────────────

/**
 * Re-exported from memory for convenience. The skills package uses the
 * same key-value storage adapter as the identity system.
 */
export type { IdentityStorageAdapter as StorageAdapter };
