import {
  collectCharCandidates,
  collectCharIntersectionCandidates,
  collectLengthCandidates,
  collectSchemaCandidates,
  collectTagCandidates,
  filterTools,
  intersectFromIndex,
  selectCandidateTools,
  selectEmbeddingCandidates,
  selectTextCandidates,
  unionFromIndex,
} from './candidates';
import {
  buildEmbeddingIndex,
  createEmbeddingBucketIndex,
  createProjectionMatrix,
  getEmbeddingBandKeys,
  getEmbeddingConfiguration,
  getEmbeddingSignatureBits,
  getRegistryEmbeddingIndex,
  removeEmbeddingBuckets,
  removeToolFromEmbeddingIndex,
} from './embedding-index';
import {
  addFieldTokens,
  addToolToTextIndex,
  createFieldTokenIndex,
  getTokenCharacters,
  getTokenGrams,
  removeFieldTokens,
  removeToolFromTextIndex,
} from './field-token-index';
import { compileCriteria, normalizeFilterValues, riskMatches } from './filters';
import {
  addToolToInvertedIndex,
  buildInvertedIndex,
  buildTextInvertedIndex,
  buildToolLookup,
  getRegistryInvertedIndex,
  getRegistryTextIndex,
  getToolLookup,
  removeToolFromInvertedIndex,
} from './indexes';
import { createMatchComparator, selectTopMatches } from './ranking-utilities';
import { createToolSummary, selectMatchResults, selectQueryResults } from './selection';
import { isToolRegistered, resolveTools } from './tool-access';

export const internalRegistryTestUtilities = {
  addFieldTokens,
  addToolToInvertedIndex,
  addToolToTextIndex,
  buildEmbeddingIndex,
  buildInvertedIndex,
  buildTextInvertedIndex,
  buildToolLookup,
  collectCharCandidates,
  collectCharIntersectionCandidates,
  collectLengthCandidates,
  collectSchemaCandidates,
  collectTagCandidates,
  collectTextCandidates: selectTextCandidates,
  compileCriteria,
  createEmbeddingBucketIndex,
  createFieldTokenIndex,
  createMatchComparator,
  createProjectionMatrix,
  createToolSummary,
  filterTools,
  getEmbeddingBandKeys,
  getEmbeddingConfiguration,
  getEmbeddingSignatureBits,
  getRegistryEmbeddingIndex,
  getRegistryInvertedIndex,
  getRegistryTextIndex,
  getTokenCharacters,
  getTokenGrams,
  getToolLookup,
  intersectFromIndex,
  isToolRegistered,
  normalizeFilterValues,
  removeEmbeddingBuckets,
  removeFieldTokens,
  removeToolFromEmbeddingIndex,
  removeToolFromInvertedIndex,
  removeToolFromTextIndex,
  resolveTools,
  riskMatches,
  selectCandidateTools,
  selectEmbeddingCandidates,
  selectMatchResults,
  selectQueryResults,
  selectTopMatches,
  unionFromIndex,
};
